package com.advatix.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonBackReference;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@Entity
@Table(name = "address")
@ApiModel(description = " All attribute of Address data ")
public class Address {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@ApiModelProperty(notes = "autoGeneratedId", hidden = true)
	@Column(name = "address_id")
	private int addressId;

	@ApiModelProperty(notes = "city name at least 2 character", required = true,position = 1)
	@NotNull(message = " city name cannot be null")
	@Column(name = "city_name")
	private String cityName;

	@ApiModelProperty(notes = "state at least 2 character", required = true,position = 2)
	@NotNull(message = "state cannot be null")
	@Column(name = "state")
	private String state;

	@ApiModelProperty(notes = "country at least 2 character", required = true,position = 3)
	@NotNull(message = " country name cannot be null")
	@Column(name = "country")
	private String country;

	@ApiModelProperty(notes = "pin code at least 2 character", required = true,position = 4)
	@NotNull(message = " pin code cannot be 0")
	@Column(name = "pincode")
	private int pincode;

	@OneToOne(mappedBy = "address")
	@ApiModelProperty(notes = "address attribute", required = true)
	@JsonBackReference
	private Student student;

	public Address() {
		// TODO Auto-generated constructor stub
	}

	public Address(String cityName, String state, String country, int pincode, Student student) {
		super();
		this.cityName = cityName;
		this.state = state;
		this.country = country;
		this.pincode = pincode;
		this.student = student;
	}

	public int getAddressId() {
		return addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public int getPincode() {
		return pincode;
	}

	public void setPincode(int pincode) {
		this.pincode = pincode;
	}

	public Student getStudent() {
		return student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Override
	public String toString() {
		return "Address [addressId=" + addressId + ", cityName=" + cityName + ", state=" + state + ", country="
				+ country + ", pincode=" + pincode + ", student=" + student + "]";
	}

}
