package com.advatix.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@Entity
@Table(name = "bmi")
@ApiModel(description = " All attribute of BMI data ")
public class Bmi {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@ApiModelProperty(notes = "autoGeneratedId")
	@Column(name = "id")
	private int id;
	
	@ApiModelProperty(notes = "at least 2 character",required = true)
	@Column(name = "name")
	@NotNull(message = "name is requried")
	private String name;
	

	@ApiModelProperty(notes = "at least 2 number",required = true)
	@Column(name = "age")
	@NotNull(message = "age is requried")
	private int age;
	
	@ApiModelProperty(notes = "at least 2 and 3 number range",required = true)
	@Column(name = "weight")
	@NotNull(message = "weight canot be null required 1 or 2 number range\"")
	private float weight;
	
	@ApiModelProperty(notes = "at least 2 number",required = true)
	@Column(name = "height")
	@NotNull(message = "height canot be null required 1 or 2 number range")
	private float height;	
	
	@Column(name="result")
	private float result;

	public Bmi() {
		// TODO Auto-generated constructor stub
	}

	public Bmi(@NotNull(message = "name is requried") String name, @NotNull(message = "age is requried") int age,
			@NotNull(message = "weight canot be null required 1 or 2 number range\"") float weight,
			@NotNull(message = "height canot be null required 1 or 2 number range") float height) {
		super();
		this.name = name;
		this.age = age;
		this.weight = weight;
		this.height = height;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public float getWeight() {
		return weight;
	}

	public void setWeight(float weight) {
		this.weight = weight;
	}

	public float getHeight() {
		return height;
	}

	public void setHeight(float height) {
		this.height = height;
	}

	public float getResult() {
		return result;
	}

	public void setResult(float result) {
		this.result = result;
	}

	@Override
	public String toString() {
		return "Bmi [id=" + id + ", name=" + name + ", age=" + age + ", weight=" + weight + ", height=" + height
				+ ", result=" + result + "]";
	}

	
	

	

}
