package com.advatix.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@Entity
@Table(name = "course")
@ApiModel(description = " All attribute of Course data")
public class Course {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@ApiModelProperty(notes = "autoGeneratedId")
	@Column(name = "course_id")
	private int courseId;

	@ApiModelProperty(notes = "course name at least 2 character", required = true)
	@Column(name = "course_name")
	private String courseName;

	@OneToOne(mappedBy = "course")
	@ApiModelProperty(notes = "course attribute", required = true)
	@JsonBackReference
	private Student student;

	public Course() {
	}

	public Course(String courseName, Student student) {
		super();
		this.courseName = courseName;
		this.student = student;
	}

	public int getCourseId() {
		return courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public String getCourseName() {
		return courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public Student getStudent() {
		return student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Override
	public String toString() {
		return "Course [courseId=" + courseId + ", courseName=" + courseName + ", student=" + student + "]";
	}

}
