package com.advatix.entities;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import io.swagger.annotations.ApiModelProperty;

@Entity
@Table(name = "product_Info")
public class ProductInfo {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@ApiModelProperty(notes = "autoGeneratedId",hidden = true)	
	@Column(name = "id")
	private int id;

	@ApiModelProperty(notes = "Product name at least 2 character", required = true)
	@Column(name = "product_name")
	private String productName;

	@ApiModelProperty(notes = "Product type: cold, Ambient, Frozen, Product", required = true)
	@Column(name = "product_type")
	private String productType;

	@ApiModelProperty(hidden = true)
	@Column(name = "weight")
	private float weight;

	@OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@ApiModelProperty(notes = "product reference", required = true)
	@JsonManagedReference
	private ProductAddress fromAddress;

	@ApiModelProperty(hidden = true)
	@Column(name = "cost")
	private float cost;

	@ApiModelProperty(hidden  = true)
	@Column(name = "delivey_of_days")
	private int deliveryOfDays;

	public ProductInfo() {
	}

	public ProductInfo(String productName, String productType, float weight, ProductAddress fromAddress, float cost,
			int deliveryOfDays) {
		super();
		this.productName = productName;
		this.productType = productType;
		this.weight = weight;
		this.fromAddress = fromAddress;
		this.cost = cost;
		this.deliveryOfDays = deliveryOfDays;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductType() {
		return productType;
	}

	public void setProductType(String productType) {
		this.productType = productType;
	}

	public float getWeight() {
		return weight;
	}

	public void setWeight(float weight) {
		this.weight = weight;
	}

	public ProductAddress getFromAddress() {
		return fromAddress;
	}

	public void setFromAddress(ProductAddress fromAddress) {
		this.fromAddress = fromAddress;
	}

	public float getCost() {
		return cost;
	}

	public void setCost(float cost) {
		this.cost = cost;
	}

	public int getDeliveryOfDays() {
		return deliveryOfDays;
	}

	public void setDeliveryOfDays(int deliveryOfDays) {
		this.deliveryOfDays = deliveryOfDays;
	}

	@Override
	public String toString() {
		return "ProductInfo [id=" + id + ", productName=" + productName + ", productType=" + productType + ", weight="
				+ weight + ", fromAddress=" + fromAddress + ", cost=" + cost + ", deliveryOfDays=" + deliveryOfDays
				+ "]";
	}

}
