package com.advatix.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@Entity
@Table(name = "product_address")
@ApiModel(description = " All attribute of product address data ")
public class ProductAddress {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@ApiModelProperty(notes = "autoGeneratedId",hidden = true)	
	@Column(name = "id")
	private int id;

	@ApiModelProperty(notes = "city name at least 2 character", required = true)
	@Column(name = "city_name")
	private String cityName;

	@ApiModelProperty(notes = "state at least 2 character", required = true)
	@Column(name = "state")
	private String state;

	@ApiModelProperty(notes = "country at least 2 character", required = true)
	@Column(name = "country")
	private String country;

	@ApiModelProperty(notes = "pin code at least 2 character", required = true)
	@Column(name = "pincode")
	private int pincode;

	@ApiModelProperty(notes = "phone no should be in 10 digit", required = true)
	@Column(name = "phone")
	private String phone;

	@OneToOne(mappedBy = "fromAddress")
	@ApiModelProperty(notes = "productInfo attribute", required = true)
	@JsonBackReference
	private ProductInfo productInfo;

	public ProductAddress() {
	}

	public ProductAddress(String cityName, String state, String country, int pincode, String phone,
			ProductInfo productInfo) {
		super();
		this.cityName = cityName;
		this.state = state;
		this.country = country;
		this.pincode = pincode;
		this.phone = phone;
		this.productInfo = productInfo;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public int getPincode() {
		return pincode;
	}

	public void setPincode(int pincode) {
		this.pincode = pincode;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public ProductInfo getProductInfo() {
		return productInfo;
	}

	public void setProductInfo(ProductInfo productInfo) {
		this.productInfo = productInfo;
	}

	@Override
	public String toString() {
		return "ProductAddress [id=" + id + ", cityName=" + cityName + ", state=" + state + ", country=" + country
				+ ", pincode=" + pincode + ", phone=" + phone + ", productInfo=" + productInfo + "]";
	}

}
